#!/bin/bash
# scripts/compound/auto-compound.sh
# Full pipeline: report -> PRD -> tasks -> implementation -> PR
# Schedule: 11:00 PM nightly via launchd

set -e

PROJECT_DIR="/Users/sjarmak/compound"
LOG_FILE="$PROJECT_DIR/logs/auto-compound.log"
SCRIPTS_DIR="$PROJECT_DIR/scripts/compound"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log "=== Starting Auto-Compound ==="

cd "$PROJECT_DIR"

# Source environment if it exists
if [ -f .env.local ]; then
  source .env.local
fi

# Fetch latest (including tonight's CLAUDE.md updates)
git fetch origin main
git reset --hard origin/main

# Find the latest prioritized report
LATEST_REPORT=$(ls -t reports/*.md 2>/dev/null | head -1)

if [ -z "$LATEST_REPORT" ]; then
  log "No reports found in reports/. Skipping."
  exit 0
fi

log "Using report: $LATEST_REPORT"

# Analyze and pick #1 priority
ANALYSIS=$("$SCRIPTS_DIR/analyze-report.sh" "$LATEST_REPORT")
PRIORITY_ITEM=$(echo "$ANALYSIS" | jq -r '.priority_item')
BRANCH_NAME=$(echo "$ANALYSIS" | jq -r '.branch_name')

if [ -z "$PRIORITY_ITEM" ] || [ "$PRIORITY_ITEM" = "null" ]; then
  log "No priority item found. Skipping."
  exit 0
fi

log "Priority: $PRIORITY_ITEM"
log "Branch: $BRANCH_NAME"

# Create feature branch
git checkout -b "$BRANCH_NAME"

# Create PRD
log "Creating PRD..."
claude -p "Create a Product Requirements Document (PRD) for: $PRIORITY_ITEM. Include user stories, acceptance criteria, technical approach, and edge cases. Save to tasks/prd-$(basename "$BRANCH_NAME").md" \
  --dangerously-skip-permissions \
  2>&1 | tee -a "$LOG_FILE"

# Convert to tasks
log "Converting PRD to tasks..."
claude -p "Read the PRD at tasks/prd-$(basename "$BRANCH_NAME").md and convert it into a structured task list in scripts/compound/prd.json. Each task should have: id, title, description, acceptance_criteria, and status (pending/in_progress/done)." \
  --dangerously-skip-permissions \
  2>&1 | tee -a "$LOG_FILE"

# Run the execution loop
log "Starting execution loop..."
"$SCRIPTS_DIR/loop.sh" 25

# Create PR
log "Creating PR..."
git push -u origin "$BRANCH_NAME"
gh pr create \
  --draft \
  --title "Compound: $PRIORITY_ITEM" \
  --base main \
  --body "Automated implementation of: $PRIORITY_ITEM

Generated by the nightly compound engineering loop.
Review logs at: logs/auto-compound.log"

log "=== Auto-Compound Complete ==="
